name: The Gathering CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      CI: true

    steps:
    - name: "📥 Checkout Repository"
      uses: actions/checkout@v4

    - name: "🐍 Setup Python 3.13"
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: "📦 Install Dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: "🧪 Run Unit Tests"
      run: |
        pytest tests/unit/ -v --tb=short

    - name: "🔄 Run E2E Tests"
      run: |
        pytest tests/e2e/ -v --tb=short

    - name: "📊 Generate Coverage Report"
      run: |
        pytest --cov=app --cov-report=term-missing --cov-report=xml
        echo "✅ Test coverage completed"